### ISSUE TITLE
adding a result folder

### ISSUE THREAD

**Issue by ModarHalimeh** [adamjgnoel/AcCoRD#1]
Hey Adam.
It would be useful if you can add an empty folder called results to the package. 
Cause without it, the user can't run the simulator "it will give an error", and there's nothing about creating such folder in the documentation. 

Best regards,
MHD

**Comment by adamjgnoel** [comment]
Thanks. It wouldn't let me commit an empty folder, so I can just add the result for the default config and commit that.

**Comment by adamjgnoel** [comment]
Done, Thanks Modar for pointing this out.
