### ISSUE TITLE
Accuracy of transitions between microscopic and mesoscopic regimes

### ISSUE THREAD

**Issue by adamjgnoel** [adamjgnoel/AcCoRD#2]
Currently, simplified transition rules are used at the hybrid interface, as described here: [http://dx.doi.org/10.1145/2800795.2800821](url)

Transition rules will be upgraded following this work: [http://arxiv.org/abs/1304.5487](url)

**Comment by ModarHalimeh** [comment]
as a side note, in v.0.3.1.1 there was actually a problem with the transition.
I tested this on v.0.4 and the problem is gone.

**Comment by adamjgnoel** [comment]
Thanks for confirming. A lot of the work on v0.4 was improving transitions between regions (in general).

**Comment by adamjgnoel** [comment]
Updated transition rules to follow the algorithms described in http://dx.doi.org/10.1137/130915844. Code now in master branch.

Transition rules are set by defining "Small Subvolumes at Hybrid Interface?" in the Simulation Control object of the configuration file. If true, then it is assumed that the size of meso subvolumes at the micro/meso interface are on the order of a micro diffusion step size. If false, then it is assumed that the size of the meso subvolumes at the interface are much greater than a micro diffusion step size.
