### ISSUE TITLE
Problem with a Sphere child region

### ISSUE THREAD

**Issue by ModarHalimeh** [adamjgnoel/AcCoRD#35]
Here are the configs i'm using to create 2 spheres as child region, each one is placed inside a rectangular one: 
%%%%%%%%%%%%%%%%%Parent Regions%%%%%%%%%%%%%%%%%%%%%%%%
"Number of Dimensions": 3,
        "Subvolume Base Size": 1e-6,
        "Region Specification": [
            {
    "Notes": "",
    "Label": "A",
    "Parent label": "",
    "Shape": "Rectangular Box",
    "Anchor X Coordinate": 0,
    "Anchor Y Coordinate": 0,  
    "Anchor Z Coordinate": 0,  
    "Integer Subvolume Size": 1,
    "Is Region Microscopic?": true,
    "Number of Subvolumes Along X": 4,
    "Number of Subvolumes Along Y": 5,
    "Number of Subvolumes Along Z": 4
            },
            {
    "Notes": "",
    "Label": "B",
    "Parent label": "",
    "Shape": "Rectangular Box",
    "Anchor X Coordinate": 4e-6,
    "Anchor Y Coordinate": 0,
    "Anchor Z Coordinate": 0,
    "Integer Subvolume Size": 1,
    "Is Region Microscopic?": true,
    "Number of Subvolumes Along X": 4,
    "Number of Subvolumes Along Y": 5,
    "Number of Subvolumes Along Z": 4
        },
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%Child Regions%%%%%%%%%%%%%%%%%%%%%%%
"Notes": "",
    "Label": "C",
    "Parent label": "A",
    "Shape": "Sphere",
    "Anchor X Coordinate": 2e-6,
    "Anchor Y Coordinate": 2e-6,
    "Anchor Z Coordinate": 2e-6,
        "Radius": 1e-6
            },
            {
    "Notes": "",
    "Label": "D",
    "Parent label": "B",
    "Shape": "Sphere",
    "Anchor X Coordinate": 6e-6,
    "Anchor Y Coordinate": 2e-6,
    "Anchor Z Coordinate": 2e-6,
    "Radius": 1e-6
            }
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

It's outputting an error that the nested regions are not properly within their parents. 
Which i assume is not right ?!

**Comment by adamjgnoel** [comment]
Can you attach the original config file? At first glance this shouldn't generate an error, but it could be that the 2 radii are "just" too big. It should work with radii 0.99999e-6 instead of 1e-6.

**Comment by ModarHalimeh** [comment]
sure i posted this part just for compactness. 

[Config.txt](https://github.com/adamjgnoel/AcCoRD/files/139679/Config.txt)

Note: Your solution worked :) 'the 0.999999e-6'

**Comment by adamjgnoel** [comment]
Ok, I won't need to run the configuration myself then.

Posting the excerpt as you did was helpful without needing the whole file.

I will fix this by adding (or in this case subtracting) the subvolume resolution value (which is about 1%) from the clearance size, so that 1e-6 will work.

**Comment by adamjgnoel** [comment]
The clearance distance between spherical and rectangular subvolumes has been modified from the ("rectangular subvolume size") to ("rectangular subvolume size" - "epsilon distance"), where the epsilon distance is currently defined as 1% of the base subvolume size.

With this change, your config file runs fine. The correction will be in the next code commit.
