### ISSUE TITLE
Active Actors: Type of Molecules released

### ISSUE THREAD

**Issue by ModarHalimeh** [adamjgnoel/AcCoRD#43]
When defining an active actor, with let's say 3 types of molecules with a release vector: [true, true , true] the actor wont actually release the 3 types when transmitting a '1', instead it will only release the first true it sees in the vector 'the first type only in this case'.
Now this might make sense, but I think it's better to add it in the 'how to define config' text file if it's not treated as a bug.

**Comment by ModarHalimeh** [comment]
[Nested_Spheres_One_Bit_W_Chemical_SEED1.txt](https://github.com/adamjgnoel/AcCoRD/files/151746/Nested_Spheres_One_Bit_W_Chemical_SEED1.txt)

[Config.txt](https://github.com/adamjgnoel/AcCoRD/files/151747/Config.txt)

example config and output files.

**Comment by adamjgnoel** [comment]
Good catch. The only modulation scheme defined right now is CSK, which by definition will only release one type of  molecule so it releases the type with the first "true" associated with it. This can be clarified in the documentation.

**Comment by adamjgnoel** [comment]
Documentation for CSK was updated some time ago. Should add another type of modulation, e.g. noise-based, that just adds the number of specified molecules (i.e., without modulating). This would be analogous to setting bit probability to 1 and having 1 bit per symbol, but will also allow multiple types of molecules

**Comment by adamjgnoel** [comment]
"Burst" modulation added to master branch code. It enables release of multiple types of molecules by a single actor, but it does not modulate any data (effectively, it always sends 1 bit symbols of value 1)
