### ISSUE TITLE
Products vector mismatch

### ISSUE THREAD

**Issue by ModarHalimeh** [adamjgnoel/AcCoRD#44]
In a scenario where chemical reactions are defined with a vector "Reactants": [1,0,0],
and products are defined with "Products": [5,10,20],

the simulator will stop responding "not an error message". 

the full section of the problem: 

"Chemical Reaction Specification": [
            {  
                "Notes": "",
                "Default Everywhere?": true,
                "Exception Regions": [],
                "Reactants": [1,0,0],
                "Products": [5,40,10],
                "Reaction Rate": 1  

```
        }
```

Another one, is a syntax error i guess.
When defining the products vector with [5,00,00] this will return an error "as if it is a syntax error"
while if the vector is replaced with [5,0,0] "which is the same" the simulator will run normally. 

-Those are counted as 2 bugs in one thread here btw :dancers:

**Comment by adamjgnoel** [comment]
There is a hard-coded limit of 4 products per reaction. This limit was to save memory in the reaction network initialization. This limit should either be documented or removed via dynamic allocation. It doesn't really make physical sense to have a huge number of products in an elementary reaction, so it's reasonable to limit the number of products.

The error with the products vector that you describe would be in the JSON code and not AcCoRD's. Presumably "00" is not valid JSON for "0". It should be sufficient to document this as a limitation.

**Comment by adamjgnoel** [comment]
Ok, there is a bug here. I tweaked the memory allocation so that the limit on the number of products should no longer apply. However, there are still some memory errors. I will investigate this further today.

**Comment by adamjgnoel** [comment]
Nevermind, the bug was unrelated to this issue and was just a typo in the latest local release.

I have relaxed the limit on the number of products to be unbounded and it appears to test fine with the reactor configuration. This correction will be included in the next release.

**Comment by adamjgnoel** [comment]
Slight qualification: number of products is limited to uint32_max

The correction has been committed to the AddSurfaceRegions branch
